spring.application.name=atividade-pontuada-v2

spring.datasource.url=jdbc:mysql://localhost:3306/db_atividade_pontuada_2
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true